name = "appi-news-github-oauth"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[vars]
GITHUB_CLIENT_ID = "Ov23li5ZlTLWwUxraTM1"
ALLOWED_ORIGIN = "https://yao-care.github.io"
OAUTH_SCOPE = "public_repo"
ADMIN_PATH = "/appi.news/admin/"
